simpleblog/urls.py
from django.contrib import admin
from django.urls import path
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name='home'),
    path('articles/', blog.views.home, name='article-list'),
    path('articles/new/', blog.views.article_add, name='article-add'),
    path('articles/<int:id>/change/', blog.views.article_edit, name='article-edit'),
    path('articles/<int:id>/delete/', blog.views.article_delete, name='article-delete'),
    path('articles/<int:id>/commentaires/', blog.views.article_commentaires, name='article-commentaires'),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image


class User(AbstractUser):
    profile_photo = models.ImageField(verbose_name='Photo de profil', null=True, blank=True)
    
    IMAGE_MAX_SIZE = (800, 800)
    
    def resize_image(self):
        if self.profile_photo:
            image = Image.open(self.profile_photo)
            image.thumbnail(self.IMAGE_MAX_SIZE)
            image.save(self.profile_photo.path)
        
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    
class Comment(models.Model):
    #author = models.ForeignKey(User) # Comme on a pas encore fait de gestion des utilisateurs, on n'utilise pas de relation Foreignkey
    author = models.CharField(max_length=50)
    content = models.TextField()
    commented_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    
    def __str__(self):
        return f"Comment by {self.author} on {self.article}"
    

blog/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    edit_article = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    class Meta:
        model = Article
        fields = ('title', 'content')
        
        
class DeleteArticleForm(forms.Form):
    delete_blog = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    
    
class CommentForm(forms.ModelForm):
    edit_comment = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    class Meta:
        model = Comment
        fields = ('author', 'content')
        widgets = {
            'content': forms.Textarea(attrs={'cols': 20, 'rows': 5}),
        }

authentication/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm, DeleteArticleForm, CommentForm

def home(request):
    articles = Article.objects.all()
    
    return render(request, 'blog/blog_list.html', context={'articles': articles})


def article_add(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('article-list')
    else:
        form = ArticleForm()
    
    return render(request, 'blog/blog_add.html', context={'form': form})


def article_edit(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('article-list')
    else:
        form = ArticleForm(instance=article)
        
    return render(request, 'blog/blog_edit.html', context={'form': form})


def article_delete(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == 'POST':
        form = DeleteArticleForm(request.POST)
        if form.is_valid():
            article.delete()
            return redirect('article-list')
    else:
        form = DeleteArticleForm()
    
    return render(request, 'blog/article_delete.html', context={'form': form})


def article_commentaires(request, id):
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.article = article
            new_comment.save()
            # Réinitialiser le formulaire après soumission
            form = CommentForm()
    else:
        form = CommentForm()
    
    context = {
        'article': article,
        'comments': comments,
        'form': form,
    }
    return render(request, 'blog/article_commentaires.html', context=context)

blog/templates/blog/article_commentaires.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}

    <div class="container">
        <div class="card shadow px-4 py-2 my-4">
            <h1 class="text-center mt-4">{{ article.title }}, <i>publié le {{ article.posted_at }}</i></h1>
            <p class="mt-3">{{ article.content }}</p>
        </div>

        <h2 class="mt-3">Commentaires</h2>
        {% for comment in comments %}
            <p>
                <strong>{{ comment.author }}</strong> : <i>{{ comment.content }}</i> - 
                <i>({{ comment.commented_at }})</i>
            </p>
        {% endfor %}

        <div class="mt-5">
            <h4 class="my-2">Votre commentaire</h4>
            <form method="post" style="width:400px">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_author" class="form-label">Votre nom</label>
                    {{ form.author | add_class:"form-control" }}
                </div>
                <div class="mb-3">
                    <label for="id_content" class="form-label">Commentaire</label>
                    {{ form.content | add_class:"form-control" }}
                </div>
                <input type="hidden" name="edit_comment" value="True" id="id_edit_comment">
                <button type="submit" class="btn btn-primary">Commenter</button>
            </form>
        </div>
    </div>

{% endblock content %}

blog/templates/blog/article_delete.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}

    <div class="container">
        <h1 class="text-center mt-4">Etes-vous sûr de vouloir supprimer ?</h1>

        <div class="card shadow px-4 py-2">
            <div class="d-flex justify-content-between">
                <button class="btn btn-default" id="annuler_suppression" onclick="annulerSuppression()">Annuler</button>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}


{% block javascript %}
    <script>
        function annulerSuppression() {
            window.location.href = "{% url 'article-list' %}";
        }
    </script>
{% endblock javascript %}

blog/templates/blog/blog_add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <h1 class="text-center mt-4">Ajout Nouveau article</h1>

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" >Ajouter</button>
        </form>
    </div>

{% endblock content %}

blog/templates/blog/blog_edit.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}

    <div class="container">
        <h1 class="text-center mt-4">Modification des articles</h1>

        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_title" class="form-label">Titre</label>
                {{ form.title | add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_content" class="form-label">Contenu</label>
                {{ form.content | add_class:"form-control" }}
            </div>
            <input type="hidden" name="edit_article" value="True" id="id_edit_article">
            <button type="submit" class="btn btn-success">Enregistrer</button>
        </form>
    </div>

{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <h1 class="text-center mt-4">Bienvenue sur notre Blog</h1>

        <h2 class="my-3">Listes des articles</h2>

        {% for article in articles %}
            <div class="card shadow px-4 py-2 my-2">
                <h4>{{ article.title }}</h4>
                <p class="my-3">{{ article.content }}</p>
                <p><strong>Date publication :</strong> <i>{{ article.posted_at }}</i></p>
                <div class="d-flex justify-content-between">
                    <div>
                        <a href="{% url 'article-commentaires' article.id %}">commentaires</a>
                    </div>
                    <div>
                        <a href="{% url 'article-edit' article.id %}">modifier</a>
                        <a href="{% url 'article-delete' article.id %}">supprimer</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

templates/base.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Blog - Simple{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-5.2.3/dist/css/bootstrap.min.css' %}">
        {% block stylesheet %}
            <!-- Inclure les liens vers les feuilles de style CSS ici -->
        {% endblock %}
    </head>
    <body>
        {% include 'partials/navbar.html' %}
        
        {% block content %}{% endblock content %}

        {# include 'partials/footer.html' #}

        <script src="{% static 'jquery-3.7.0.min.js' %}"></script>
        <script src="{% static 'bootstrap-5.2.3/dist/js/bootstrap.bundle.min.js' %}"></script>
        {% block javascript %}
            <!-- Inclure les scripts JavaScript ici -->
        {% endblock %}
    </body>
</html>

templates/partials/footer.html
<!-- Section Contact (Footer) -->
<footer id="contact" class="bg-light py-2 px-4" >
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-4">
                <h2>Contactez-nous</h2>
                <p>Si vous avez des questions ou des commentaires, n'hésitez pas à nous contacter :</p>
                <ul>
                    <li>Email: info@mairie-ouani.com</li>
                    <li>Téléphone: +269 394 04 59</li>
                    <!-- Ajoutez d'autres informations de contact ici -->
                </ul>
            </div>
            <div class="col-sm-12 col-md-4">
                <!-- Ajoutez ici un formulaire de contact -->
                <form action="#" method="post">
                    {% csrf_token %}
                    <!-- Ajoutez les champs du formulaire ici -->
                    <label for="message_contact" class="control-label">Message</label>
                    <input type="text" id="message_contact" class="form-control">
                    <button type="submit" class="btn btn-primary mt-2">Envoyer</button>
                </form>
            </div>
            <div class="col-sm-12 col-md-4">
                <!-- Ajoutez ici des liens vers les pages d'inscription et de connexion -->
                <a href="#">S'inscrire</a>
                <a href="#">Se connecter</a>
            </div>
        </div>
    </div>
</footer>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Simple-Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'article-list' %}">Articles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'article-add' %}">Nouveau Article</a>
          </li>
          {%  if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Profil</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Déconnexion</a>
            </li>  
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="#">Inscription</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Connexion</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>